### ISSUE TITLE
tiny problems

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [elastos/Elastos.ORG.ElaPay#4]
1. in orderIdDbRetriever.js
```
subQuery["amountAsDouble"] = dbTxNewRecords[i].elaamount;
```
we only need 8 decimal .
```
subQuery["amountAsDouble"] = Math.round(parseFloat(dbTxNewRecords[i].elaamount)*100000000)/100000000
```

2. the code below seems not working . when i am visit the api . no Related log displayed . 
```
system.use(morgan('dev')) 
```
> example : 
>> if i visit http://elapay-test.elastos.org:3002/  there should be logs like    
```Get http://elapay-test.elastos.org:3002/  2018:05:25 14:23:20```

3. the length problem as we discussed before. 
```
TypeError: Cannot read property 'length' of undefined
0|index    |     at /opt/ela_pay/Elastos.ELA.Pay-develop/server/services/bcjobs/fetchblocks.js:57:91
```
4. after starting server for a while starting to show errors like this . 
```
From file fetchblocks.js:  connection 2410 to localhost:27017 timed out
MongoNetworkError: connection 2410 to localhost:27017 timed out
Stopping background timer in file  from file detailsCallbackPost.js
```
5. and when i am click checkout button . here is the error 
```
0|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|index    | MongoError: server instance pool was destroyed
0|index    |     at basicWriteValidations (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb-core/lib/topologies/server.js:636:41)
0|index    |     at Server.insert (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb-core/lib/topologies/server.js:737:16)
0|index    |     at Server.insert (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/topologies/topology_base.js:315:25)
0|index    |     at executeBatch (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/bulk/unordered.js:486:23)
0|index    |     at executeBatches (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/bulk/unordered.js:521:5)
0|index    |     at executeOperation (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/utils.js:408:22)
0|index    |     at UnorderedBulkOperation.execute (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/bulk/unordered.js:616:10)
0|index    |     at bulkWrite (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/collection.js:627:8)
0|index    |     at executeOperation (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/utils.js:408:22)
0|index    |     at Collection.insertMany (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/collection.js:512:10)
0|index    |     at Collection.insert (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb/lib/collection.js:784:15)
0|index    |     at NativeCollection.(anonymous function) [as insert] (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:139:28)
0|index    |     at model.Model.$__handleSave (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongoose/lib/model.js:158:21)
0|index    |     at model.Model.$__save (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongoose/lib/model.js:227:8)
0|index    |     at /opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/kareem/index.js:276:8
0|index    |     at _next (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/kareem/index.js:102:16)
0|index    |     at process.nextTick (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/kareem/index.js:424:38)
0|index    |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by SharedMocha** [comment]
Issues 1,3,4,5 are fixed.

**Comment by SharedMocha** [comment]
Issue 2 fixed

**Comment by xiaomingfuckeasylife** [comment]
when i start the server .  the error displayed
```
0|index    | Worker 2596 is online
0|index    | Worker 2554 is online

0|index    | Server listen to :3002
0|index    | Server listen to :3002
0|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|index    | MongoNetworkError: connection 0 to localhost:27017 timed out
0|index    |     at Socket.<anonymous> (/opt/ela_pay/Elastos.ELA.Pay-develop/server/node_modules/mongodb-core/lib/connection/connection.js:258:7)
0|index    |     at Object.onceWrapper (events.js:313:30)
0|index    |     at emitNone (events.js:106:13)
0|index    |     at Socket.emit (events.js:208:7)
0|index    |     at Socket._onTimeout (net.js:420:8)
0|index    |     at ontimeout (timers.js:482:11)
0|index    |     at tryOnTimeout (timers.js:317:5)
0|index    |     at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by hoangnv1203** [comment]
When I run on local, I do not have any issue. @SharedMocha  Could you check your local again.

**Comment by SharedMocha** [comment]
Closing this issue as defect 5 is not reproducible consistently.
